services:
  - type: web
    name: unilorin-ams
    env: node
    plan: starter
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm run db:migrate && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: HARDWARE_API_KEY
        sync: false
      - key: HARDWARE_SECRET
        sync: false
    healthCheckPath: /api/ping 